workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_MODE: release
      ios_signing:
        certificates:
          - Shift7_Distribute_Certificate      # شهادة التوزيع
        provisioning_profiles:
          - Shift7_Distribute_Certificate     # App Store Distribution profile
    integrations:
      app_store_connect: shift7                # integration معرف في Codemagic

    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Clean iOS Pods
        script: |
          cd ios
          pod deintegrate
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Set up keychain
        script: |
          keychain initialize
          keychain add-certificates

      - name: Apply code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          # Build iOS IPA only (skip Android completely)
          # This command builds only iOS, not Android
          flutter build ipa --release \
          --build-name=1.0.4 \
          --build-number=10 \
          --export-method=app-store
          
          # Verify IPA was created
          if [ ! -f "build/ios/ipa/*.ipa" ]; then
            echo "IPA file not found!"
            ls -la build/ios/ipa/
            exit 1
          fi
          echo "IPA build successful!"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - tester
