workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        provisioning_profiles:
          - Shift7_Distribute_Certificate
        certificates:
          - Visual_Distribute_Certificate
    integrations:
      app_store_connect: moy

    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Clean iOS Pods
        script: |
          cd ios
          pod deintegrate
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize

      - name: Use system default keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings
        script: |
          xcode-project use-profiles

      - name: Flutter build ipa with versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.4 \
          --build-number=10 \
          --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - tester
          - Sufian
          - VISUAL
