platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  # Flutter plugins are automatically managed by Flutter
  # No need to add them manually here

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
